import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Footer from '@/components/footer/Footer';
import PrimaryHeader from '@/components/header/PrimaryHeader';
import NavBar from '@/components/layout/NavBar';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-dvh`}>
        <PrimaryHeader />
        <div className={`w-full flex-row min-h-auto`}>
          <NavBar />
          {children}
        </div>
        <div className={`mt-auto`}>
          <Footer />
        </div>
      </body>
    </html>
  );
}